# Prettier Configuration
# https://prettier.io/docs/en/options.html

semi: true
singleQuote: true
tabWidth: 2
useTabs: false
trailingComma: es5
printWidth: 100
bracketSpacing: true
arrowParens: always
endOfLine: lf
